# # Eh is to deal with exception in running
# try:
#     print(10/0)
# except Exception as e:
#     print(e)
# finally:
#     print("Done")
# print("we are learning exception handeling")


# # We don't always use EH it depends on system

# def add(x,y):
#     if y==0:
#         raise Exception ("y shouldn't be 0")
#     return x+y

# try:
#     print(add(10,0))
# except Exception as e:
#     print(e)

